"""add company policies table and clarification flow enums

Revision ID: f58b68bc0080
Revises: 47fa67724fdf
Create Date: 2026-08-22 22:05:52.655288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
# revision identifiers, used by Alembic.
revision: str = 'f58b68bc0080'
down_revision: Union[str, Sequence[str], None] = '47fa67724fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('policy_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_drafts', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("ALTER TYPE ticketstatus ADD VALUE IF NOT EXISTS 'AWAITING_CLARIFICATION'")
    op.execute("ALTER TYPE ticketeventtype ADD VALUE IF NOT EXISTS 'CLARIFICATION_REQUESTED'")
    op.execute("ALTER TYPE ticketeventtype ADD VALUE IF NOT EXISTS 'CLARIFICATION_ANSWERED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_drafts', 'analysis')
    op.drop_table('company_policies')
    # ### end Alembic commands ###
